CREATE OR REPLACE TABLE PRODUCTS
 (
     ID int NOT NULL AUTO_INCREMENT,
     DESCRIPTION varchar(30) NOT NULL,
     PRIMARY KEY (ID)
 );

 CREATE OR REPLACE TABLE FEES
 (
     ID smallint NOT NULL AUTO_INCREMENT,
     PERCENTAGE DECIMAL(4,2) NOT NULL,
     PRIMARY KEY (ID)
 );

 CREATE OR REPLACE TABLE BRANDS
 (
     ID SMALLINT NOT NULL AUTO_INCREMENT,
     DESCRIPTION VARCHAR(30) NOT NULL,
     PRIMARY KEY (ID)
 );

 CREATE OR REPLACE TABLE CURRENCIES
 (
     ID SMALLINT NOT NULL AUTO_INCREMENT,
     DESCRIPTION CHAR(3) NOT NULL,
     PRIMARY KEY (ID)
 );

 CREATE OR REPLACE TABLE PRICES
 (
     ID SMALLINT NOT NULL AUTO_INCREMENT,
     BRAND_ID SMALLINT NOT NULL,
     START_DATE DATETIME NOT NULL,
     END_DATE DATETIME NOT NULL,
     FEE_ID SMALLINT NOT NULL,
     PRODUCT_ID INT NOT NULL,
     PRIORITY TINYINT NOT NULL,
     PRICE DECIMAL(4,2) NOT NULL,
     CURRENCY_ID SMALLINT NOT NULL,
     PRIMARY KEY (ID),
     FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID),
     FOREIGN KEY (FEE_ID) REFERENCES FEES(ID),
     FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID),
     FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCIES(ID)
 );